# periodic table
# default config file

server:
  port: 3000

i18n:
  languages: [ en, de ]
  default: en

default:
  theme: light
  lists: [ group, period, set, block, phase, natural_occurrence, goldschmidt, crystal_structure, magnetic_ordering ]