# periodic table
# default config file

server:
  port: 3000

i18n:
  languages: [ en, de ]
  default: en

site:
  theme: light
  lists: [
    group, period, set, era, block, phase, natural_occurrence, basicity, goldschmidt,
    radioactivity, crystal_structure, magnetic_ordering, superconductivity
  ]
  scales:
    standard_atomic_weight:
      key: standard_atomic_weight
      label: standard-atomic-weight
      scheme: _ice
    atomic_mass:
      key: atomic_mass
      label: atomic-mass
      scheme: _ice
    radius_empirical:
      key: radius.empirical
      label: empirical-radius
      scheme: _fire
    radius_calculated:
      key: radius.calculated
      label: calculated-radius
      scheme: _fire
    radius_covalent:
      key: radius.covalent
      label: covalent-radius
      scheme: _fire
    radius_vdw:
      key: radius.vdw
      label: vdw-radius
      scheme: _fire
    hardness_mohs:
      key: hardness.mohs
      label: mohs-hardness
      scheme: _grayscale
      round: floor
      step: 1
      min: 0
      max: 10
    hardness_brinell:
      key: hardness.brinell
      label: brinell-hardness
      scheme: _grayscale
    hardness_vickers:
      key: hardness.vickers
      label: vickers-hardness
      scheme: _grayscale
    elastic_young:
      key: elastic.young
      label: young-elastic
      scheme: _ice
    elastic_rigidity:
      key: elastic.rigidity
      label: rigidity-elastic
      scheme: _ice
    elastic_bulk:
      key: elastic.bulk
      label: bulk-elastic
      scheme: _ice
    elastic_poisson:
      key: elastic.poisson
      label: poisson-elastic
      scheme: _ice
    sc_temp:
      key: sc_temp
      label: sc_temp
      scheme: _fire
  props: [
    radioactive, natural, native, vital, mononuclidic, stable, noble, semiconductor,
    light, heavy, rare, platinum, refractory, artificial, synthetic, antiquity
  ]

maintenance:
  databases: [ elements, isotopes ]