# periodic table
# default config file

server:
  baseURL: https://pse-info.de
  port: 3000
  cookieAge: 1.0e+10

maintenance:
  databases: [
    elements, spectrum
  ]

i18n:
  default: en
  list: [
    en, de
  ]

themes:
  default: light
  list: [
    light, dark
  ]

pt:
  offset: 3

lists: [
  group, period, set, era, block, phase, natural_occurrence,
  basicity, goldschmidt, radioactivity, crystal_structure,
  magnetic_ordering, superconductivity
]

properties: [
  radioactive, natural, native, vital, mononuclidic,
  stable, noble, semiconductor, light, heavy, rare,
  platinum, refractory, artificial, synthetic, antiquity
]

scales:
  standard_atomic_weight:
    key: standard_atomic_weight
    label: standard-atomic-weight
    scheme: _ice
  atomic_mass:
    key: atomic_mass
    label: atomic-mass
    scheme: _ice
  radius_empirical:
    key: radius.empirical
    label: empirical-radius
    scheme: _fire
    scaling: true
  radius_calculated:
    key: radius.calculated
    label: calculated-radius
    scheme: _fire
    scaling: true
  radius_covalent:
    key: radius.covalent
    label: covalent-radius
    scheme: _fire
    scaling: true
  radius_vdw:
    key: radius.vdw
    label: vdw-radius
    scheme: _fire
    scaling: true
  density:
    key: density
    label: density
    scheme: _fire
  molar_volume:
    key: molar_volume
    label: molar_volume
    scheme: _fire
  sound_speed:
    key: sound_speed
    label: sound_speed
    scheme: _ice
    log: true
  temp_melting:
    key: temperature.melting
    label: melting-temp
    scheme: _ice_reverse
  temp_boiling:
    key: temperature.boiling
    label: boiling-temp
    scheme: _fire
  temp_liquid:
    key: temperature.liquid
    label: liquid-temp
    scheme: _ice
  temp_sublimation:
    key: temperature.sublimation
    label: sublimation-temp
    scheme: _fire
  temp_triple:
    key: temperature.triple
    label: triple-temp
    scheme: _fire
  temp_critical:
    key: temperature.critical
    label: critical-temp
    scheme: _fire
  temp_transition:
    key: temperature.transition
    label: transition-temp
    scheme: _fire
  enthalpy_fusion:
    key: enthalpy.fusion
    label: fusion-enthalpy
    scheme: _fire
    scaling: true
  enthalpy_vaporisation:
    key: enthalpy.vaporisation
    label: vaporisation-enthalpy
    scheme: _fire
    scaling: true
  enthalpy_atomisation:
    key: enthalpy.atomisation
    label: atomisation-enthalpy
    scheme: _fire
    scaling: true
  heat_capacity:
    key: heat.heat_capacity
    label: heat_capacity
    scheme: _fire
    min: 100
    max: 2500
  thermal_conductivity:
    key: heat.thermal_conductivity
    label: thermal_conductivity
    scheme: _fire
  thermal_expansion:
    key: heat.thermal_expansion
    label: thermal_expansion
    scheme: _fire
    log: true
    scaling: true
  work_function:
    key: heat.work_function
    label: work_function
    scheme: _fire
    scaling: true
  hardness_mohs:
    key: hardness.mohs
    label: mohs-hardness
    scheme: _ice
    round: floor
    step: 1
    min: 0
    max: 10
  hardness_brinell:
    key: hardness.brinell
    label: brinell-hardness
    scheme: _ice
  hardness_vickers:
    key: hardness.vickers
    label: vickers-hardness
    scheme: _ice
  elastic_young:
    key: elastic.young
    label: young-elastic
    scheme: _ice
    scaling: true
  elastic_rigidity:
    key: elastic.rigidity
    label: rigidity-elastic
    scheme: _ice
    scaling: true
  elastic_bulk:
    key: elastic.bulk
    label: bulk-elastic
    scheme: _ice
    scaling: true
  elastic_poisson:
    key: elastic.poisson
    label: poisson-elastic
    scheme: _ice
    scaling: true
  electrical_conductivity:
    key: electrical.conductivity
    label: electrical_conductivity
    scheme: _ice_reverse
    min: 0.9e+6
    max: 5.0e+7
  electrical_resistivity:
    key: electrical.resistivity
    label: electrical_resistivity
    scheme: _ice
    log: true
  optical_reflectivity:
    key: optical.reflectivity
    label: reflectivity-optical
    scheme: _ice
  optical_refractive_index:
    key: optical.refractive_index
    label: refractive_index-optical
    scheme: _ice
    log: true
  standard_potential:
    key: standard_potential
    label: standard-potential
    scheme: _fire
  negativity_pauling:
    key: negativity.pauling
    label: pauling-negativity
    scheme: _fire
  negativity_sanderson:
    key: negativity.sanderson
    label: sanderson-negativity
    scheme: _fire
  negativity_allred:
    key: negativity.allred
    label: allred-negativity
    scheme: _fire
  negativity_mulliken:
    key: negativity.mulliken
    label: mulliken-negativity
    scheme: _fire
  negativity_allen:
    key: negativity.allen
    label: allen-negativity
    scheme: _fire
  price:
    key: price
    label: price
    scheme: _ice
    log: true
    scaling: true

abundances:
  universe:
    mass: 2.0e+49
    icon: satellite_alt
  sun:
    mass: 1.989e+30
    icon: sunny
  meteorite:
    mass: 1.0e+3
    icon: destruction
  crust:
    mass: 2.77e+22
    icon: public
  water:
    mass: 1.37e+18
    icon: water_drop
  stream:
    mass: 1.6e+16
    icon: waves
  human:
    mass: 70.0
    icon: accessibility_new