# periodic table
# default config file

server:
  port: 3000

i18n:
  languages: [ en, de ]
  default: en

site:
  theme: light
  lists: [
    group, period, set, era, block, phase, natural_occurrence, basicity, goldschmidt,
    radioactivity, crystal_structure, magnetic_ordering, superconductivity
  ]
  scales:
    hardness_mohs:
      key: hardness.mohs
      label: mohs-hardness
      scheme: _grayscale
      round: floor
      step: 1
      min: 0
      max: 10
    hardness_brinell:
      key: hardness.brinell
      label: brinell-hardness
      scheme: _grayscale
    hardness_vickers:
      key: hardness.vickers
      label: vickers-hardness
      scheme: _grayscale
  props: [
    radioactive, natural, native, vital, mononuclidic, stable, noble, semiconductor,
    light, heavy, rare, platinum, refractory, artificial, synthetic, antiquity
  ]

maintenance:
  databases: [ elements, isotopes ]