# periodic table
# default config file

server:
  port: 3000

i18n:
  languages: [ en, de ]
  default: en

site:
  theme: light
  lists: [
    group, period, set, era, block, phase, natural_occurrence, basicity, goldschmidt,
    radioactivity, crystal_structure, magnetic_ordering, superconductivity
  ]
  scales: []
  props: [
    radioactive, natural, native, vital, mononuclidic, stable, noble, semiconductor,
    light, heavy, rare, platinum, refractory, artificial, synthetic, antiquity
  ]

maintenance:
  databases: [ elements, isotopes ]