# periodic table
# default config file

server:
  port: 3000

i18n:
  languages: [ en, de ]
  default: en

site:
  theme: light
  lists: [
    group, period, set, block, phase, natural_occurrence, basicity, goldschmidt,
    crystal_structure, magnetic_ordering, superconductivity
  ]
  scales: []
  props: [
    radioactive, natural, native, vital, clean, stable, noble, light, heavy,
    rare, platinum, refractory, artificial
  ]

maintenance:
  databases: [ elements, isotopes ]