module.exports = [
    [ '/:locale{/}', 'start' ],
    [ '/:locale/404{/}', '404' ],
    [ '/:locale/abundance/:abundance{/}', 'abundance' ],
    [ '/:locale/abundances{/}', 'abundances' ],
    [ '/:locale/data{/}', 'data' ],
    [ '/:locale/decay/:isotope{/}', 'decay' ],
    [ '/:locale/element/:element{/}', 'element' ],
    [ '/:locale/glossary{/}', 'glossary' ],
    [ '/:locale/ionization{/}', 'ionization' ],
    [ '/:locale/isotopes/:element{/}', 'isotopes' ],
    [ '/:locale/list/:list{/}', 'list' ],
    [ '/:locale/list/:list/:prop{/}', 'list' ],
    [ '/:locale/lists{/}', 'lists' ],
    [ '/:locale/nuclides{/}', 'nuclides' ],
    [ '/:locale/privacy{/}', 'privacy' ],
    [ '/:locale/prop/:property{/}', 'prop' ],
    [ '/:locale/props{/}', 'props' ],
    [ '/:locale/quiz{/}', 'quiz' ],
    [ '/:locale/search{/}', 'search' ],
    [ '/:locale/scale/:scale{/}', 'scale' ],
    [ '/:locale/scales{/}', 'scales' ],
    [ '/:locale/sitemap{/}', 'sitemap' ],
    [ '/:locale/spectrum{/}', 'spectrum' ],
    [ '/:locale/tools{/}', 'tools' ]
];